# Generated by Django 3.1.3 on 2021-09-15 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_elementtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementtype',
            name='balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elementtype',
            name='recurring',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.PositiveIntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ElementEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remain_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('elementType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.elementtype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='payroll.employee')),
            ],
        ),
    ]
