# Generated by Django 3.1.3 on 2021-09-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_employeeaction_payrollaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.PositiveIntegerField(),
        ),
    ]
